version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: img_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Uses named volume

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: flask-backend
    restart: always
    depends_on:
      - db
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://myuser:mypass@db:5432/img_store
      JWT_SECRET_KEY: JWT_SECRET_KEY
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
